### ISSUE TITLE
(Feature Request) Make use of the "share" function

### ISSUE THREAD

**Issue by 5c0tt-b0t** [Kaned1as/Man-Man#25]
Me again!
Use the text share function, thats when you highlight some text, a small popup above the highlighted text appears with a "share" button.
Then this app would be seamless, allowing it to also be launched via other apps, for example, a terminal (like Termux), a web browser, a text editor etc, rather than:
- Leave app
- Open app drawer
- Select man man
- Type out query

### Examples:
- In Termux
  - highlight "coreutils"
  - hit share button
  - select man man

- In a web browser
  - the same as above, but also:
  - offer to open links for `https://man7.org/linux/man-pages/` in your app instead, then we can choose to tap "always" so man page links are always opened via man man.

Your app is already **amazing**, after the above (and my other feature request), it will be **PERFECT!**

**Once again, thank you for your time & effort, its really appreciated!!!** so glad to have this app back 4 years, the recent update is incredible!

**Comment by Adonai** [comment]
Ok this seems interesting, I'll have a look

**Comment by Kaned1as** [comment]
Hmm you're right, this _is_ the good feature. I'll work on implementing it.

**Comment by Kaned1as** [comment]
Implemented in 9957c8896f45f7e4456097838ccddf08b9cb4788
